# Generated by Django 3.0.8 on 2020-08-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='score',
            new_name='ques_answered',
        ),
        migrations.AddField(
            model_name='student',
            name='attempt_for_q',
            field=models.SmallIntegerField(blank=True, default=5, null=True),
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='Qna',
        ),
    ]
