# Generated by Django 3.0.8 on 2020-08-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200821_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='shown_at_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
